name: Deploy to firebase test 3

'on': pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v11.16.0
      with: 
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}